name: Print Special Folders

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  # 1. Desktop Platforms (Windows, macOS, Linux)
  desktop-run:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Run App
      run: dotnet run --project specialdirs.csproj

  # 2. Android Mobile Run
  android-mobile-run:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Enable KVM group permissions
      run: |
        echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
        sudo udevadm control --reload-rules
        sudo udevadm trigger --name-match=kvm

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Install .NET Android Workload
      run: |
        dotnet workload install android
        dotnet tool install Microsoft.DotNet.XHarness.CLI --global --add-source "https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-eng/nuget/v3/index.json" --version "11.0.0-prerelease*"

    - name: Run on Android Emulator
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 34
        arch: x86_64
        target: google_apis
        script: |
          dotnet build specialdirs.csproj -c Release /p:TargetAndroid=true /p:CheckEolWorkloads=false
          xharness android run --app="bin/Release/net8.0-android/specialdirs.apk" --package-name="com.ahenyao.specialdirs" --output-directory="android-results"

  # 3. iOS Mobile Run
  ios-mobile-run:
    runs-on: macos-14
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Install .NET iOS Workload
      run: |
        dotnet workload install ios
        dotnet tool install Microsoft.DotNet.XHarness.CLI --global --add-source "https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-eng/nuget/v3/index.json" --version "11.0.0-prerelease*"

    - name: Run on iOS Simulator
      run: |
        dotnet build specialdirs.csproj -c Release -r iossimulator-x64 /p:TargetiOS=true /p:CheckEolWorkloads=false
        xharness apple run --app="bin/Release/net8.0-ios/iossimulator-x64/specialdirs.app" --targets="ios-simulator-64" --output-directory="ios-results"